

#nombre de los servicios que agregar a este compose:
#   Microservicios BackEnd:
#       - UserService (mi microservicio de java spring)
#       - MusicService (mi microservicio de java spring)
#       - NotificationService (mi microservicio de java spring)
#       - DonationService (mi microservicio de java spring)
#   Microservicios FrontEnd:
#       - FrontEnd (mi microservicio de Angular 16)
#   Containers que venia corriendo de manera local para que funcionara t-odo localmente:
#       para UserService:
#           - UserDb
#           - UserMiniO
#       para MusicService:
#           - MusicDb
#           - MusicMiniO
#       para NotificationService:
#           - NotificationDb
#       para DonationService:
#           - DonationDb
#
#